[package]
name = "envoy-proto-collect"
authors = ["Rafael Lemos <contact@flemosr.com"]
edition = "2021"
license = "Apache-2.0"
publish = false
version = "0.1.0"

[[bin]]
name = "collect-protos"
path = "src/main.rs"

[dependencies]
glob = "0.3"
