name: CI

on:
  push:
    branches: [ "main" ]
  pull_request: {}
  merge_group:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hecrj/setup-rust-action@v2
      with:
        components: rustfmt
    - run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hecrj/setup-rust-action@v2
      with:
        components: clippy
    - uses: taiki-e/install-action@protoc
    - uses: Swatinem/rust-cache@v2
    - run: cargo clippy --workspace --all-features --all-targets
